# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # USB SSD — existing data, not managed by disko.
  # Podman depends on it: containers bind-mount from /mnt.
  fileSystems."/mnt" = {
    device = "/dev/disk/by-uuid/3b95b690-13a1-4052-bc81-ade5b51f2de1";
    fsType = "ext4";
    options = ["nofail" "x-systemd.device-timeout=90" "x-systemd.automount"];
  };
}
