{
  imports = [
    ./helix.nix
    ./noctalia.nix
    ./niri.nix
    ./yazi.nix
    ./fish.nix
    ./foot.nix
    ./fuzzel.nix
    ./git.nix
    ./starship.nix
    ./ssh.nix
    ./zen.nix
    ./steam.nix
    ./discord.nix
    ./opencode.nix
    ./lazygit.nix
    ./clapper.nix
    ./imv.nix
    ./rustdesk.nix
    ./java.nix
    ./prismlauncher.nix
    ./flatpak.nix
  ];
}
